version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      timezone: "Asia/Tokyo"
      time: "00:00"
    reviewers:
      - "kelvin27315"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      timezone: "Asia/Tokyo"
      time: "00:00"
    reviewers:
      - "kelvin27315"
